### ISSUE TITLE
Only read resource yaml files once on startup

### ISSUE THREAD

**Issue by wookie184** [discord-python/site#1209]
Currently resources are loaded and parsed etc. in the `__init__` of the resources view here:
https://github.com/python-discord/site/blob/4ce61bddff9fd459b769305f302dcd9eb8ded395/pydis_site/apps/resources/views.py#L28-L36

I assume the intention here is for this to be run once on application startup, but in reality it seems this is run every time the `/resources` view is accessed. This leads to non-ideal performance. From sentry:
![image](https://github.com/python-discord/site/assets/22353562/b1604cd6-3e8d-4979-ac1e-4df2439fb6da)

Cloudflare caching makes this issue less noticeable on the actual website, but it will still be an issue sometimes so is probably worth improving.

**Comment by RohanJnr** [comment]
This can be solved using django [AppConfig.ready() method](https://docs.djangoproject.com/en/5.0/ref/applications/#django.apps.AppConfig.ready). If no one is working on it, I can patch it.

**Comment by wookie184** [comment]
Thanks for doing this @RohanJnr :)
