### ISSUE TITLE
Remove Subdomains From Bot Guide

### ISSUE THREAD

**Issue by HassanAbouelela** [discord-python/site#611]
#526 and python-discord/bot#1630 removed subdomains from the bot and site this week, but we still need to update the guides to reflect those changes.

What needs to be done:
- Under the [configure the bot](https://www.pythondiscord.com/pages/guides/pydis-guides/contributing/bot/#configure-the-bot) section, we will need to remove the mentions of subdomains, and instead mention query paths (`localhost:8000/api` for instance).
- We should delete the guide on [setting up hosts](https://www.pythondiscord.com/pages/guides/pydis-guides/contributing/hosts-file/).

> ❗ Work on this does not need to start until #591 is merged to avoid conflicts

**Comment by Kronifer** [comment]
@HassanAbouelela once this is possible I'd like to give this a try

**Comment by HassanAbouelela** [comment]
Hey @Kronifer, after making this issue, I found out Zig is adding it to his PR, which I linked to this.
