### ISSUE TITLE
Resource Suggestion: Dear PyGui

### ISSUE THREAD

**Issue by bandit-masked** [discord-python/site#656]
**Resource name**\
Dear PyGui

**Resource location**\
https://github.com/hoffstadt/DearPyGui

**Payment type**\
Free (MIT license)

**Why it should be included**\
Dear PyGui is a fast and powerful cross-platform Graphical User Interface Toolkit for Python with minimal dependencies, available under a permissive MIT license. It fits in with GUI frameworks such as Tkinter, PySimpleGui, PyQt and WxPython. Each framework has its strengths and weaknesses. Dear PyGUI stands out in its combination of versatility (e.g. traditional widgets, plotting, textures/graphical features, node editor), theming, tooling (style editor, debugging tools, documentation built in) performance (written in C/C++ and using the GPU) while being lightweight. Because of its versatility, it's suitable for a whole range of applications, from small games to scientific apps, from music players to managing data pipelines. Even though development on Dear PyGui only started in July 2020, the project already has gained over 7,000 stars, which indicates that people find use for it. 

A few examples of apps made with Dear PyGui can be seen here.
https://github.com/hoffstadt/DearPyGui/wiki/Dear-PyGui-Showcase

**Potential limitations**\
There is version-controlled documentation for Dear PyGUI that covers most of its functionality here.
https://dearpygui.readthedocs.io/en/latest/index.html

Code quality is high and actively maintained with multiple commits per week and regular releases. However, there are still quite a few details, e.g. how to set a third axis on a graph, that are not documented well or at all. There is an active Discord community of approximately 1,000 members for support (see https://discord.gg/tyE7Gu4).

The core developers take inspiration from game engines, so it does not have an OOP orientation. There are developers who have created OOP wrappers for DPG. The lack of OOP is confusing to some who are used to other libraries, such as Tkinter, but appealing to others, beginners and advanced users alike.

Another potential drawback could be that the functionality for creative and fluid layouts might need more work on the developers part compared to some other frameworks, such as Electron.

Kindly let me know if you have any questions about Dear PyGui.

**Comment by swfarnsworth** [comment]
Thank you for taking interest in our resources. The resources page is for curating media for learning Python and how to do different things in Python; it is not a collection of recommended libraries.

**Comment by bandit-masked** [comment]
I was referring to the following page that links to Kivy, Pandas3D and Pyglet or their Discord servers.

https://www.pythondiscord.com/resources/?topics=user-interface

If more appropriate, I'd suggest a link to the Dear PyGui Discord server:  https://discord.gg/tyE7Gu4

Apologies if I misunderstood. I don't mean to argumentative, but to explain why I thought it might be appropriate given the references to these other comparable libraries.

**Comment by swfarnsworth** [comment]
I see. It would appear that some of the entries under user interfaces are written as though they're featuring the library themselves, even though in some cases, the associated Discord server is the actual resource.

I'll bring this up with staff members who are experienced with GUI design. Thanks!

**Comment by bandit-masked** [comment]
Thank you. If it turns out there is another resource page that is a better fit, please let me know.

**Comment by swfarnsworth** [comment]
Thank you for suggesting this resource, and for your patience in awaiting our decision. We don't feel that the Discord server associated with this library is of sufficient benefit to our users, and so we won't be featuring Dear PyGui or the associated Discord server at this time. By our observation, questions about Dear PyGui in our server are infrequent, and so we don't see added value in listing an alternative location in which to ask about the library.

I realize you may feel that if other Discord servers related to UI/UX libraries are featured, that the server for Dear PyGui should be included. Many of the resources that we currently list are based on year-old decisions that I can't speak to. It may be that there are reasons for including them of which I am not aware, or that we need to revisit what UI/UX resources we feature.

I do not know where else you might be able to promote Dear PyGui.

Thank you.
