### ISSUE TITLE
Consider dropping deploy preview support for redirects app

### ISSUE THREAD

**Issue by jchristgit** [discord-python/site#680]
Do we need previews of the legacy redirects?

If not, we may be able to remove a lot of code from the redirects app.

**Comment by jchristgit** [comment]
@HassanAbouelela do you know if we can action this issue somehow?

**Comment by HassanAbouelela** [comment]
Part of the issue is we use some redirects even within the main site, particularly in things like nav. Removing the redirects from static builds makes parts of the site non-functional.

**Comment by jchristgit** [comment]
Does this still apply if we fix #681 ?

**Comment by HassanAbouelela** [comment]
It would definitely resolve the issue in the short term, but we'd encounter the same issue in the future if we change other links.
