### ISSUE TITLE
Fix events page inconsistency.

### ISSUE THREAD

**Issue by kosayoda** [discord-python/site#725]
I noticed there are a couple spots that still infer that we have 2 jams a year, so feel free to fix those in this PR if you wish, otherwise we can update that content later.

_Originally posted by @minalike in https://github.com/python-discord/site/pull/724#pullrequestreview-1011461547_

**Comment by sue-m-oh** [comment]
The two spots I noticed:
- "one during the summer and sometimes one during the winter" (I believe this isn't the case anymore, we're pretty squarely in 1 a year territory I believe) 
https://www.pythondiscord.com/events/ 

- "Our Code Jams happen twice a year. We have a Winter Jam and a Summer Jam."
https://www.pythondiscord.com/events/code-jams/#how-often-do-these-happen

I found the code jam page itself difficult to find (an easy to miss link on the events page): https://www.pythondiscord.com/events/code-jams/

Maybe we can link it in an "Relevant Links" link block on the side bar of the events page. 

- Minor typo: TUIS > TUIs
