### ISSUE TITLE
Update the code jam event page to include the theme of code jam 9

### ISSUE THREAD

**Issue by Kronifer** [discord-python/site#749]
The current [code jam](https://www.pythondiscord.com/events/code-jams/) events page does not have the theme of code jam 9 listed yet, as shown here: ![Screenshot_20220722-135025_Samsung Internet.jpg](https://user-images.githubusercontent.com/44979306/180505301-dab5e7cd-cb60-4b0e-973e-30a617365dd3.jpg)

I could fix this really quickly, as it's just a small change.

**Comment by ChrisLovering** [comment]
This is part of https://github.com/python-discord/site/pull/748
