### ISSUE TITLE
Already passed important dates not crossed in events/code jam 2022

### ISSUE THREAD

**Issue by Ibrahim2750mi** [discord-python/site#761]
In the site's [code jam page](https://www.pythondiscord.com/events/code-jams/9/), the two dates shown below should be crossed as their time period is over but they are not. If possible I would like to work on this issue myself.
![2022-08-11_21-43](https://user-images.githubusercontent.com/74553450/184180415-a86300c6-4a56-4fc3-bd92-fdf31e70d80f.png)

**Comment by wookie184** [comment]
@Ibrahim2750mi yes, if you'd like to open a PR that would be appreciated!

**Comment by Ibrahim2750mi** [comment]
@wookie184 do you know where is/are html file/files related to the issue located, I tried to find but wasn't able to.

**Comment by whispersofthedawn** [comment]
> @wookie184 do you know where is/are html file/files related to the issue located, I tried to find but wasn't able to.

https://github.com/python-discord/site/blob/main/pydis_site/templates/events/pages/code-jams/9/_index.html#L30-L31
