### ISSUE TITLE
Add field to Infraction model for jump link to infraction message.

### ISSUE THREAD

**Issue by vivekashok1221** [discord-python/site#801]
Relevant bot issue: [bot#2329](https://github.com/python-discord/bot/issues/2329)

**Comment by jchristgit** [comment]
Don't we delete the message from the bot about infractions manually created? Or was this changed at some point?

**Comment by vivekashok1221** [comment]
I'm not sure what you mean.

**Comment by jchristgit** [comment]
As far as I remember, when mods infracted someone, the message of the bot confirming the infraction would get deleted after a moment. A quick search seems to suggest this was changed though, since the bot messages persist

**Comment by vivekashok1221** [comment]
Oh, okay.
We will be storing the link to the mod's message here though.
