### ISSUE TITLE
Contributing Guidelines-Writing Good Commit Messages Page Not Found

### ISSUE THREAD

**Issue by DivyanshuBist** [discord-python/site#809]
As mentioned in the Title,
[Writing Good Commit Messages](https://www.pythondiscord.com/pages/guides/pydis-guides/contributing/contributing-guidelines.md/commit-messages/) page is showing 404 error page not found.This url is accessed from the [Contributing Guidelines](https://www.pythondiscord.com/pages/guides/pydis-guides/contributing/contributing-guidelines.md/) page.

## To Reproduce the error
- Go to Python Discord Contributing Guidelines Page (mentioned above) and click on Writing Good Commit Messages .

**Comment by onerandomusername** [comment]
Interesting, is there not a link check workflow that checks that all links are valid?

**Comment by DivyanshuBist** [comment]
Quick Fix: 
Inside [Contributing Guidelines Markdown File](https://github.com/python-discord/site/blob/main/pydis_site/apps/content/resources/guides/pydis-guides/contributing/contributing-guidelines.md)
change the `writing good commit message` url to `./contributing-guidelines/commit-messages.md`
I think it will work because commit-message.md is inside the contributing-guidelines folder.
Maybe we can add the tag of good first issue.
