### ISSUE TITLE
Add the Python Org's Python Tutorial to Resources

### ISSUE THREAD

**Issue by brad90four** [discord-python/site#852]
The resources page does not include the tutorial linked on the python.org site [here](https://docs.python.org/3/tutorial/)

I think we should include it as a free tutorial source.

**Comment by Assile** [comment]
Some questions I have about my own code for this are:
1. Is it OK to use an image directly from their website as the logo?
2. Is it OK to use a trademarked logo for this?

**Comment by wookie184** [comment]
> Is it OK to use a trademarked logo for this?

I think there are certain rules about how you can *modify* the logo, but since we're not doing that there should be no issue.
