### ISSUE TITLE
Remove mention of the removed #partners channel

### ISSUE THREAD

**Issue by mudkipdev** [discord-python/site#868]
Under the "Partners" role in the [server roles page](https://www.pythondiscord.com/pages/server-info/roles/), there is some text about a #partners channel that does not exist anymore, as well as a comment about being Discord partnered.

![image](https://user-images.githubusercontent.com/86132148/216877316-4637f798-0c12-4cb3-8647-634bb2714a62.png)

**Comment by whispersofthedawn** [comment]
Thanks! We should also remove the comment about being part of Discord partners, since that's no longer applicable.

**Comment by HassanAbouelela** [comment]
The channel still exists, but it’s always been private. The note below can be updated though.

**Comment by lemonsaurus** [comment]
Maybe you're thinking of #partner-discussion, @HassanAbouelela? #partners, which used to list all our partnered communities, does not exist anymore. 

I do agree with this issue, but I'm not sure exactly what this should be changed _to_. We're discussing it among the @python-discord/admins, so let's hold off on this until then.

**Comment by HassanAbouelela** [comment]
Yup, you're correct, I was confused.

**Comment by jchristgit** [comment]
@lemonsaurus did you find a good place to change it to?
