### ISSUE TITLE
Events page on website showing outdated information

### ISSUE THREAD

**Issue by Ibrahim2750mi** [discord-python/site#872]
On this [page](https://www.pythondiscord.com/events/) of the website, it is showing that Code Jam 2022 is underway while its finished.
![2023-02-10_13-22](https://user-images.githubusercontent.com/74553450/218034341-e36ca978-100c-4b21-bae0-aff9f120fdd2.png)

**Comment by ichard26** [comment]
Good timing! I independently discovered this issue and brought it up in a staff channel a few days ago, but nothing happened. So I filed a PR to simply remove this call-out. Thanks for reporting 🦆
