### ISSUE TITLE
Events calendar on website is outdated

### ISSUE THREAD

**Issue by Ibrahim2750mi** [discord-python/site#873]
The events calendar on this [page](https://www.pythondiscord.com/events/) is outdated.
![2023-02-10_13-32](https://user-images.githubusercontent.com/74553450/218035802-df9a2757-3151-450b-b9a0-83ff19199300.png)

**Comment by Ibrahim2750mi** [comment]
The modification should be to atleast update the PyWeek info and change the year to 2023. For the code jam, I think it should be changed to just text and remove the redirecting link?

**Comment by Ibrahim2750mi** [comment]
> The modification should be to atleast update the PyWeek info and change the year to 2023. For the code jam, I think it should be changed to just text and remove the redirecting link?

@ichard26 Can I make a pr according to this or it is being internally discussed? Also assign the issue to me

**Comment by mbaruh** [comment]
@Ibrahim2750mi I assigned it to you. Summer code jam and Pixels dates are TBD, and the rest of the links should be removed. Thanks!
