### ISSUE TITLE
Contributing to Sir Lancebot page missing important env variable

### ISSUE THREAD

**Issue by Ibrahim2750mi** [discord-python/site#880]
https://www.pythondiscord.com/pages/guides/pydis-guides/contributing/sir-lancebot/#environment-variables This fragment of the page displays _needed_ environment variables to run the bot but it is missing an environment variable for the trashcan emoji, which is needed to run the `help` command. And as the help command is common to test the bot, its essential. Same in this [page](https://www.pythondiscord.com/pages/guides/pydis-guides/contributing/sir-lancebot/env-var-reference/#general-variables/) too.

Also, I would like to be assigned this issue.

**Comment by wookie184** [comment]
Sounds like a good idea, I've assigned you

**Comment by shtlrs** [comment]
I think the same issue occurs in bot too, doesn't it ?

**Comment by Ibrahim2750mi** [comment]
> I think the same issue occurs in bot too, doesn't it ?

It is explicitly mentioned in `config.yml` under `style.emoji` to atleast change the trashcan emoji and `style.emoji` is mentioned on the python bot contributing page as needed to run the bot.
