### ISSUE TITLE
Contributing to Sir Lancebot->Envrionment variables->Description has mistakes 

### ISSUE THREAD

**Issue by Ibrahim2750mi** [discord-python/site#881]
## Under this [fragment](https://www.pythondiscord.com/pages/guides/pydis-guides/contributing/sir-lancebot/#environment-variables) and this [page](https://www.pythondiscord.com/pages/guides/pydis-guides/contributing/sir-lancebot/env-var-reference/#general-variables)

+ ### `Admin` and `Helper` role is misspelled in the [fragment](https://www.pythondiscord.com/pages/guides/pydis-guides/contributing/sir-lancebot/#environment-variables).

Here the `Admin` role is typed as Admins and the `Helper` role as Helpers.

![2023-02-21_01-53](https://user-images.githubusercontent.com/74553450/220192470-f473af42-9c34-4f84-9a64-d50792a46760.png)

+ ### Description has missed changing the colors of roles and channels in the [page](https://www.pythondiscord.com/pages/guides/pydis-guides/contributing/sir-lancebot/env-var-reference/#general-variables).

The channel names and roles should be having the color `#a02136` but instead they are just plain black text.

![2023-02-21_02-04_1](https://user-images.githubusercontent.com/74553450/220194976-00fd47a1-154e-45ac-bb83-5b0ab14d586c.png)
![2023-02-21_02-05](https://user-images.githubusercontent.com/74553450/220194996-7773adb8-bbb9-4ea2-a97a-86018359c019.png)

Again, I would like to be assigned this issue.

**Comment by wookie184** [comment]
The names of team roles on the server are plural (`Admins`, `Helpers`). A reason for this is that it looks better in pings (because when you ping you're pinging multiple people), and also in the member list (because it's a heading for multiple people with the role). I think it would make most sense to be consistent with that.

The codeblock additions sound good.
