### ISSUE TITLE
The setup page of sir-lancebot mentions Python 3.9 is needed but poetry needs 3.10

### ISSUE THREAD

**Issue by henri-climber** [discord-python/site#891]
Hey there,

![grafik](https://user-images.githubusercontent.com/96082972/221872607-0d2206ad-2b43-440c-9b25-6d334288e5af.png)
Here (https://www.pythondiscord.com/pages/guides/pydis-guides/contributing/sir-lancebot/) it says Python 3.9 is needed to run sir-lancebot but when trying to run the bot with poetry it says that you need python 3.10. On the setup page of the other bot it says 3.10 so it's correct there.

Should be a quick fix.

**Comment by HassanAbouelela** [comment]
You’re correct, it needs updating. Would you like to fix it?

**Comment by henri-climber** [comment]
I haven't set up the project yet and for now my plan is to contribute on the bots only since i don't have any experience with django. So feel free to fix it.

**Comment by HassanAbouelela** [comment]
No worries, thanks for reporting.
