### ISSUE TITLE
New page on using cogs/extensions in discord.py

### ISSUE THREAD

**Issue by n0Oo0Oo0b** [discord-python/site#901]
From #695

**Comment by jchristgit** [comment]
@n0Oo0Oo0b thank you for your suggestion. Could you clarify how this would differ from the documentation on this topic by discord.py itself? We don't want to duplicate information on the site that may run out of date as discord.py itself updates.

**Comment by n0Oo0Oo0b** [comment]
> @n0Oo0Oo0b thank you for your suggestion. Could you clarify how this would differ from the documentation on this topic by discord.py itself? We don't want to duplicate information on the site that may run out of date as discord.py itself updates.

The current documentation (for [Cogs](https://discordpy.readthedocs.io/en/latest/ext/commands/cogs.html) and [Extensions](https://discordpy.readthedocs.io/en/latest/ext/commands/extensions.html)) and the [examples in the d.py repo](https://github.com/Rapptz/discord.py/tree/master/examples) don't have a complete example/guide on combining the two; I think having one on the site would be more useful and easier to understand for some people.

It would also include best practices for structuring those files and how you can automatically load extensions in a directory.

**Comment by jchristgit** [comment]
Sorry for the delay here. If discord.py has documentation on the two topics but not their combination then I feel it would be better to contribute it upstream?

**Comment by n0Oo0Oo0b** [comment]
I see, thanks for the feedback.
