### ISSUE TITLE
Centralize community rules

### ISSUE THREAD

**Issue by shtlrs** [discord-python/site#944]
Currently, the same rules are persisted in 2 different places
`pydis_site/apps/api/views.py`  and `pydis_site/apps/content/resources/rules.md`

Over the past month or so, we've had two rule updates in one of the files only, leaving the other forgotten.
It would be nice to put the rules in one place only in order to avoid missing out on one over the other.

**Note**
I'm not even sure this is something we'd want to do, so just putting it out there (@jchristgit you're the site master, so you might have better scope knowledge here)

An idea off the top of my head is:
Since one is put in an `.md` file, we can't really achieve intepolation of the content of that file.
So maybe the view can parse the file & extract the rules based on their numbers and maps them to a tuple along with the keywords.

**Comment by jchristgit** [comment]
I do think we should definitely find a way to keep these in sync.

As an initial workaround for this, I will add a simple unit test that will compare the rules returned by the API with the rules in the file.

**Comment by jchristgit** [comment]
@shtlrs do you think #950 was a satisfactory fix or do we want more solutions here?

**Comment by shtlrs** [comment]
I think that does it good sir.

A unit test adds no extra maintenance cost for whatever solution we would have opted for.

I'll close this now.

Thank you master!
