### ISSUE TITLE
Duplicated GitHub link for tag pages

### ISSUE THREAD

**Issue by hedyhli** [discord-python/site#963]
Oops, looks like none of us tested the tags links 😅 

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/50042066/236679428-2e7f2098-0d41-4498-ad97-5ba6b932304b.png">

[Page link](https://www.pythondiscord.com/pages/tags/args-kwargs/)

The edit-on-gh link should probably be hidden on tags, it does not point to the right URL but the pre-existing GitHub icon link does, since it uses the [base URL from Tag model](https://github.com/python-discord/site/blob/748a170be5f576b6e0e6b72cead0cafc0c32190e/pydis_site/apps/content/models/tag.py#L45).

Or maybe remove the GitHub icon and fix the edit-on-gh link for tags.

Perhaps this is due to the source files are in resources directory but the views are in content directory?

[Snippet of HTML for the button](https://github.com/python-discord/site/blob/748a170be5f576b6e0e6b72cead0cafc0c32190e/pydis_site/templates/content/tag.html#LL14C9-L16C15)

<details>
<summary>trivial</summary>
just so happened to have stumbled across the tag links while checking out how the new edit-on-gh links look like on the live page. absolutely not arising from the fact that our tags have some frequent mentioning in the dev-log recently, haha
</details>

**Comment by jchristgit** [comment]
Thanks for the report! I opened a PR that fixes this by hiding the link on tags.
